import type { Stretch, StretchingProgram } from "./types";

const STRETCH_LIBRARY: Record<string, Stretch> = {
    "cross-body-shoulder": {
        id: "cross-body-shoulder",
        name: "Cross-Body Shoulder Stretch",
        duration: 35,
        description: "Pull one arm across the chest to open the rear shoulder and upper back.",
        targetAreas: ["rear delts", "posterior shoulder", "upper back"],
        cues: [
            "Keep the shoulder down while you gently pull the arm across.",
            "Think about length, not cranking the joint into end range.",
        ],
        benefits: ["eases pressing tightness", "restores shoulder reach"],
        commonMistakes: [
            "Shrugging the shoulder toward the ear.",
            "Twisting the torso instead of isolating the shoulder.",
        ],
        regression: "Reduce the pull and hold the elbow closer to the chest.",
        progression: "Pair with slow scapular protraction / retraction between holds.",
        equipment: ["None"],
    },
    "overhead-tricep": {
        id: "overhead-tricep",
        name: "Overhead Tricep Stretch",
        duration: 35,
        description: "Reach one hand down the back and guide the elbow overhead for tricep and lat length.",
        targetAreas: ["triceps", "lats", "long head shoulder tissues"],
        cues: [
            "Keep ribs down instead of leaning backward.",
            "Let the elbow point up before gently drawing it in.",
        ],
        benefits: ["helps overhead comfort", "offsets heavy pressing volume"],
        commonMistakes: [
            "Arching the low back to fake more range.",
            "Forcing the elbow inward aggressively.",
        ],
        regression: "Use a smaller range with the hand behind the head instead of between the shoulder blades.",
        progression: "Add gentle side-bending away from the stretched arm.",
        equipment: ["None"],
    },
    "doorway-chest": {
        id: "doorway-chest",
        name: "Doorway Chest Stretch",
        duration: 40,
        description: "Use a wall or door frame to open the pecs and front delts after pressing.",
        targetAreas: ["chest", "front delts", "biceps tendon"],
        cues: [
            "Keep the shoulder blade tucked gently down the back.",
            "Rotate the torso away instead of jamming the shoulder forward.",
        ],
        benefits: ["opens postural tightness", "helps recover from push sessions"],
        commonMistakes: [
            "Driving the shoulder head forward into the joint.",
            "Going too high with the arm and irritating the front shoulder.",
        ],
        regression: "Drop the elbow lower and reduce torso rotation.",
        progression: "Run two positions: arm slightly below shoulder height and slightly above.",
        equipment: ["Door frame", "Wall"],
    },
    "thread-the-needle": {
        id: "thread-the-needle",
        name: "Thread the Needle",
        duration: 40,
        description: "A thoracic rotation stretch that opens the upper back and rear shoulder.",
        targetAreas: ["thoracic spine", "rear shoulder", "mid-back"],
        cues: [
            "Reach long with the threaded arm and let the ribs rotate.",
            "Keep hips stacked over the knees while the upper back turns.",
        ],
        benefits: ["restores rotation", "helps overhead and bench setup positions"],
        commonMistakes: [
            "Shifting the hips too far back and losing the thoracic focus.",
            "Forcing the neck into the movement.",
        ],
        regression: "Place a pad under the shoulder and shorten the range.",
        progression: "Pause and breathe fully into the upper back.",
        equipment: ["None"],
    },
    "lat-prayer": {
        id: "lat-prayer",
        name: "Lat Prayer Stretch",
        duration: 35,
        description: "Sink the chest down with hands supported to lengthen the lats and long head triceps.",
        targetAreas: ["lats", "triceps", "mid-back"],
        cues: [
            "Keep the ribs tucked instead of collapsing through the low back.",
            "Reach the hands away while sitting the hips back slightly.",
        ],
        benefits: ["improves overhead reach", "helps post-pull stiffness"],
        commonMistakes: [
            "Arching hard in the low back.",
            "Letting the shoulders shrug up toward the ears.",
        ],
        regression: "Use a higher bench, box, or chair to reduce the angle.",
        progression: "Offset one hand at a time to bias each lat separately.",
        equipment: ["Bench", "Chair", "Wall"],
    },
    "wall-slides": {
        id: "wall-slides",
        name: "Wall Slides",
        duration: 30,
        description: "Glide the forearms up a wall to train upward rotation and serratus control.",
        targetAreas: ["serratus", "upper back", "shoulders"],
        cues: [
            "Keep ribs stacked and forearms heavy on the wall.",
            "Reach up without shrugging through the neck.",
        ],
        benefits: ["improves shoulder mechanics", "great desk-reset drill"],
        commonMistakes: [
            "Arching the back to reach higher.",
            "Letting the wrists and forearms peel away from the wall.",
        ],
        regression: "Use a smaller range and focus on clean upward rotation.",
        progression: "Add a lift-off at the top if control is solid.",
        equipment: ["Wall"],
    },
    "hamstring-fold": {
        id: "hamstring-fold",
        name: "Hamstring Stretch",
        duration: 40,
        description: "A long hamstring hold that targets the back of the thighs without rounding aggressively.",
        targetAreas: ["hamstrings", "calves"],
        cues: [
            "Lead with a hip hinge instead of rounding the spine first.",
            "Keep the front foot flexed to add calf tension if helpful.",
        ],
        benefits: ["post-leg recovery", "helps hinge depth and comfort"],
        commonMistakes: [
            "Forcing the chest down by rounding through the back.",
            "Locking the knee so hard that the hamstring never relaxes.",
        ],
        regression: "Bend the knee slightly or elevate the hips.",
        progression: "Add contract-relax reps before the final hold.",
        equipment: ["None"],
    },
    "couch-stretch": {
        id: "couch-stretch",
        name: "Couch Stretch",
        duration: 40,
        description: "A deep quad and hip-flexor opener that is excellent after squats, lunges, and long desk days.",
        targetAreas: ["quads", "hip flexors", "front hip"],
        cues: [
            "Squeeze the glute on the back leg before leaning upright.",
            "Stay tall instead of chasing range with lumbar extension.",
        ],
        benefits: ["reduces front-hip tightness", "supports squat and split-squat positions"],
        commonMistakes: [
            "Arching the low back excessively to feel more stretch.",
            "Starting too upright and getting crushed immediately.",
        ],
        regression: "Move the knee farther from the wall or support yourself with the hands.",
        progression: "Reach the same-side arm overhead once the base position is stable.",
        equipment: ["Wall", "Bench"],
    },
    "pigeon-pose": {
        id: "pigeon-pose",
        name: "Pigeon Pose",
        duration: 45,
        description: "A glute-focused stretch for the back hip that also helps external rotation tolerance.",
        targetAreas: ["glutes", "deep hip rotators"],
        cues: [
            "Square the hips as much as possible before folding forward.",
            "Keep the front shin at an angle that feels controlled, not forced.",
        ],
        benefits: ["helps after leg days", "good for hip stiffness and sitting-heavy weeks"],
        commonMistakes: [
            "Trying to force the front shin parallel immediately.",
            "Collapsing all the weight onto one side of the pelvis.",
        ],
        regression: "Use a seated figure-four or support the hip with a block or cushion.",
        progression: "Add gentle forward folds with long exhales.",
        equipment: ["None"],
    },
    "adductor-rock-backs": {
        id: "adductor-rock-backs",
        name: "Adductor Rock Backs",
        duration: 35,
        description: "A dynamic groin and inner-thigh drill that opens hips without requiring extreme range.",
        targetAreas: ["adductors", "hips", "groin"],
        cues: [
            "Keep the spine long while sitting the hips back.",
            "Turn the extended-leg foot however your hips feel best.",
        ],
        benefits: ["helps squat depth", "reduces groin tightness before lower-body work"],
        commonMistakes: [
            "Rounding forward instead of hinging back.",
            "Pushing so deep that the groin grips harder.",
        ],
        regression: "Shorten the backward rock and support with yoga blocks.",
        progression: "Pause in the back position and breathe into the groin.",
        equipment: ["None"],
    },
    "ankle-dorsiflexion-rocks": {
        id: "ankle-dorsiflexion-rocks",
        name: "Ankle Dorsiflexion Rocks",
        duration: 30,
        description: "Drive the knee over the toes in a controlled way to improve ankle mobility for squats and lunges.",
        targetAreas: ["ankles", "calves", "achilles"],
        cues: [
            "Keep the heel heavy while the knee travels forward.",
            "Aim for smooth rocks instead of forcing a max stretch.",
        ],
        benefits: ["improves squat depth", "helps split squat comfort and knee travel"],
        commonMistakes: [
            "Letting the heel pop up immediately.",
            "Collapsing the arch as the knee moves forward.",
        ],
        regression: "Shorten the distance from the wall and move more slowly.",
        progression: "Add a longer pause at the front edge of the range.",
        equipment: ["Wall"],
    },
    "calf-wall-stretch": {
        id: "calf-wall-stretch",
        name: "Calf Wall Stretch",
        duration: 35,
        description: "A straight-leg calf stretch to open the gastroc and improve ankle comfort.",
        targetAreas: ["calves", "achilles"],
        cues: [
            "Press the heel down while keeping toes pointed forward.",
            "Use the hips to shift forward, not just the shoulders.",
        ],
        benefits: ["supports ankle mobility", "helps after running, walking, and leg sessions"],
        commonMistakes: [
            "Turning the foot out too much and losing the calf line.",
            "Bouncing the heel instead of settling into the stretch.",
        ],
        regression: "Shorten the stance and bend the back knee slightly.",
        progression: "Use a step for more range once the wall version is easy.",
        equipment: ["Wall"],
    },
    "cat-cow": {
        id: "cat-cow",
        name: "Cat-Cow",
        duration: 45,
        description: "A simple spinal wave that restores movement through the thoracic and lumbar segments.",
        targetAreas: ["thoracic spine", "lumbar spine", "neck"],
        cues: [
            "Move one vertebra at a time instead of rushing between end positions.",
            "Coordinate the breath with the motion to get more range without strain.",
        ],
        benefits: ["great warm-up", "helps reset stiffness after lifting or sitting"],
        commonMistakes: [
            "Making the movement too fast and sloppy.",
            "Forcing neck extension instead of moving through the whole spine.",
        ],
        regression: "Reduce the range and slow the breathing cadence.",
        progression: "Pause in each shape for a breath cycle.",
        equipment: ["None"],
    },
    "childs-pose": {
        id: "childs-pose",
        name: "Child's Pose",
        duration: 45,
        description: "A gentle reset for the hips, back, and shoulders that also encourages slower breathing.",
        targetAreas: ["lats", "low back", "hips"],
        cues: [
            "Reach long through the fingertips while sitting the hips back.",
            "Use long exhales to let the torso soften deeper into the floor.",
        ],
        benefits: ["good cooldown reset", "pairs well with breathing work"],
        commonMistakes: [
            "Forcing the hips to the heels when the knees or ankles hate it.",
            "Shrugging the shoulders while reaching forward.",
        ],
        regression: "Place a cushion between hips and heels or widen the knees more.",
        progression: "Walk the hands side to side to bias each lat.",
        equipment: ["None"],
    },
    "downward-dog": {
        id: "downward-dog",
        name: "Downward Dog",
        duration: 40,
        description: "A full posterior-chain stretch that also loads the shoulders and upper back.",
        targetAreas: ["calves", "hamstrings", "lats", "shoulders"],
        cues: [
            "Push the floor away first, then gently drive the hips up and back.",
            "Bend the knees enough to keep the spine long before chasing heel contact.",
        ],
        benefits: ["full-body opener", "excellent bridge between upper and lower recovery work"],
        commonMistakes: [
            "Rounding the back to force the heels down.",
            "Dumping into the shoulders without active reach.",
        ],
        regression: "Bend the knees more and shorten the stance.",
        progression: "Pedal the heels or alternate single-leg emphasis.",
        equipment: ["None"],
    },
    "cobra-stretch": {
        id: "cobra-stretch",
        name: "Cobra Stretch",
        duration: 35,
        description: "A front-body opener for abs, hip flexors, and chest with gentle spinal extension.",
        targetAreas: ["abdominals", "front hip", "chest"],
        cues: [
            "Press through the hands while keeping the shoulders away from the ears.",
            "Use only as much extension as feels smooth and supported.",
        ],
        benefits: ["balances heavy hinging and sitting", "opens the front line of the body"],
        commonMistakes: [
            "Jamming the low back by forcing height.",
            "Shrugging hard and crowding the neck.",
        ],
        regression: "Use sphinx position on the forearms.",
        progression: "Add a gentle side bend for the obliques and lats.",
        equipment: ["None"],
    },
    "worlds-greatest-stretch": {
        id: "worlds-greatest-stretch",
        name: "World's Greatest Stretch",
        duration: 45,
        description: "A full-body mobility drill combining lunge, thoracic rotation, and hamstring work.",
        targetAreas: ["hip flexors", "hamstrings", "thoracic spine", "adductors"],
        cues: [
            "Sink into the lunge first before reaching and rotating.",
            "Move slowly through each phase instead of rushing through the transitions.",
        ],
        benefits: ["excellent warm-up", "covers many common mobility restrictions at once"],
        commonMistakes: [
            "Treating it like cardio and blowing through the positions.",
            "Letting the front foot cave inward during the lunge.",
        ],
        regression: "Place the back knee down and reduce rotation range.",
        progression: "Add a hamstring hinge before returning to the lunge.",
        equipment: ["None"],
    },
    "ninety-ninety-switches": {
        id: "ninety-ninety-switches",
        name: "90/90 Hip Switches",
        duration: 40,
        description: "A seated hip-rotation drill that trains internal and external rotation without heavy load.",
        targetAreas: ["hips", "glutes", "deep rotators"],
        cues: [
            "Sit tall before switching side to side.",
            "Rotate from the hips instead of collapsing through the spine.",
        ],
        benefits: ["great hip prep", "useful for lifters who feel stuck in squat and split-squat positions"],
        commonMistakes: [
            "Leaning back and losing the hip challenge.",
            "Forcing the knees down instead of earning the range.",
        ],
        regression: "Support the hands behind the torso.",
        progression: "Hover the feet during transitions to add control.",
        equipment: ["None"],
    },
    "wrist-extensor": {
        id: "wrist-extensor",
        name: "Wrist Extensor Stretch",
        duration: 25,
        description: "A simple forearm and wrist opener for lifters who spend a lot of time gripping bars, handles, and keyboards.",
        targetAreas: ["forearms", "wrists"],
        cues: [
            "Straighten the elbow and gently flex the wrist until the forearm lights up.",
            "Keep the shoulder relaxed while the hand moves.",
        ],
        benefits: ["helps after lots of curls, carries, and typing", "pairs well with desk-reset sessions"],
        commonMistakes: [
            "Pulling too hard into the wrist joint.",
            "Bending the elbow and losing the forearm stretch.",
        ],
        regression: "Use a smaller range and shorter hold.",
        progression: "Add light finger extension between holds.",
        equipment: ["None"],
    },
    "deep-squat-pry": {
        id: "deep-squat-pry",
        name: "Deep Squat Pry",
        duration: 35,
        description: "Sit into a supported deep squat and gently pry the hips and ankles open.",
        targetAreas: ["ankles", "hips", "adductors"],
        cues: [
            "Use a counterbalance or support if needed so you can stay tall.",
            "Shift gently side to side to explore the hips without forcing them.",
        ],
        benefits: ["excellent squat prep", "helps if machine-free leg work demands more bottom-end mobility"],
        commonMistakes: [
            "Falling into lumbar rounding and hanging out there.",
            "Trying to sit all the way down before the ankles and hips are ready.",
        ],
        regression: "Hold onto a sturdy support or elevate the heels.",
        progression: "Add a small reach or thoracic rotation in the bottom.",
        equipment: ["Wall", "Counterweight optional"],
    },
    "neck-glides": {
        id: "neck-glides",
        name: "Neck Glides",
        duration: 25,
        description: "Gentle neck mobility to undo screen-time stiffness without cranking the cervical spine.",
        targetAreas: ["neck", "upper traps"],
        cues: [
            "Move slowly and stay below pain or pinching sensations.",
            "Think of lengthening through the crown of the head as you move.",
        ],
        benefits: ["good for desk reset days", "helps remove excess tension before upper-body training"],
        commonMistakes: [
            "Rolling aggressively through the neck.",
            "Forcing end ranges instead of staying controlled.",
        ],
        regression: "Perform only tiny nods and side glides.",
        progression: "Pair with slow shoulder blade circles.",
        equipment: ["None"],
    },
};

const stretch = (id: keyof typeof STRETCH_LIBRARY) => STRETCH_LIBRARY[id];

export const StretchingPrograms: StretchingProgram[] = [
    {
        id: "upper-body-stretch",
        name: "Upper Body Mobility",
        focusAreas: ["chest", "shoulders", "lats", "thoracic spine"],
        bestFor: ["post push day", "desk posture reset", "overhead comfort"],
        difficulty: "Easy",
        equipment: ["Mostly none", "Wall / door frame optional"],
        stretches: [
            stretch("cross-body-shoulder"),
            stretch("overhead-tricep"),
            stretch("doorway-chest"),
            stretch("thread-the-needle"),
            stretch("lat-prayer"),
            stretch("wall-slides"),
        ],
    },
    {
        id: "lower-body-stretch",
        name: "Lower Body Flexibility",
        focusAreas: ["hamstrings", "quads", "hips", "ankles", "calves"],
        bestFor: ["post leg day", "squat recovery", "tight hips from sitting"],
        difficulty: "Moderate",
        equipment: ["Mostly none", "Wall optional"],
        stretches: [
            stretch("hamstring-fold"),
            stretch("couch-stretch"),
            stretch("pigeon-pose"),
            stretch("adductor-rock-backs"),
            stretch("ankle-dorsiflexion-rocks"),
            stretch("calf-wall-stretch"),
        ],
    },
    {
        id: "full-body-stretch",
        name: "Full Body Flow",
        focusAreas: ["spine", "hips", "shoulders", "hamstrings"],
        bestFor: ["active recovery day", "morning reset", "general mobility work"],
        difficulty: "Easy",
        equipment: ["None"],
        stretches: [
            stretch("cat-cow"),
            stretch("worlds-greatest-stretch"),
            stretch("downward-dog"),
            stretch("childs-pose"),
            stretch("cobra-stretch"),
            stretch("ninety-ninety-switches"),
        ],
    },
    {
        id: "desk-reset-flow",
        name: "Desk Reset Flow",
        focusAreas: ["neck", "upper back", "wrists", "hips"],
        bestFor: ["screen-heavy days", "travel recovery", "quick midday reset"],
        difficulty: "Easy",
        equipment: ["Wall optional"],
        stretches: [
            stretch("neck-glides"),
            stretch("wall-slides"),
            stretch("doorway-chest"),
            stretch("thread-the-needle"),
            stretch("wrist-extensor"),
            stretch("childs-pose"),
        ],
    },
    {
        id: "squat-depth-reset",
        name: "Squat Depth Reset",
        focusAreas: ["ankles", "hips", "adductors", "quads"],
        bestFor: ["before leg sessions", "machine-free squat training", "mobility bottlenecks"],
        difficulty: "Focused",
        equipment: ["Wall optional", "Counterweight optional"],
        stretches: [
            stretch("deep-squat-pry"),
            stretch("ankle-dorsiflexion-rocks"),
            stretch("adductor-rock-backs"),
            stretch("couch-stretch"),
            stretch("calf-wall-stretch"),
            stretch("ninety-ninety-switches"),
        ],
    },
];
