import type { ExerciseEquipment, ExerciseWiki } from "./wikiData";

export interface ExerciseEnhancement {
    equipment: ExerciseEquipment[];
    difficulty?: "Beginner" | "Intermediate" | "Advanced";
    movementPattern?: string;
    bestFor?: string[];
    setupChecklist?: string[];
    freeWeightAlternatives?: string[];
    minimalEquipmentAlternatives?: string[];
    homeGymFriendly?: boolean;
}

export const EXERCISE_ENHANCEMENTS: Record<string, ExerciseEnhancement> = {
    "Bench Press": {
        equipment: ["barbell", "bench"],
        difficulty: "Intermediate",
        movementPattern: "horizontal press",
        freeWeightAlternatives: ["Dumbbell Bench Press", "Floor Press", "Push-ups"],
        minimalEquipmentAlternatives: ["Push-ups", "Floor Press"],
        bestFor: ["primary push strength", "progressive overload", "upper-body mass"],
    },
    "Seated DB Press": {
        equipment: ["dumbbell", "bench"],
        difficulty: "Beginner",
        movementPattern: "vertical press",
        freeWeightAlternatives: ["Barbell OHP", "Landmine Press", "Arnold Press"],
        minimalEquipmentAlternatives: ["Barbell OHP", "Landmine Press"],
        homeGymFriendly: true,
    },
    "Incline DB Press": {
        equipment: ["dumbbell", "bench"],
        difficulty: "Beginner",
        movementPattern: "incline press",
        freeWeightAlternatives: ["Incline Barbell Press", "Dumbbell Bench Press", "Push-ups"],
        minimalEquipmentAlternatives: ["Push-ups", "Floor Press"],
        homeGymFriendly: true,
    },
    "Cable Lateral Raises": {
        equipment: ["cable"],
        difficulty: "Beginner",
        movementPattern: "shoulder abduction",
        freeWeightAlternatives: ["Lateral Raises", "Bent-Over Rear Delt Flyes", "Landmine Press"],
        minimalEquipmentAlternatives: ["Lateral Raises", "Bent-Over Rear Delt Flyes"],
        homeGymFriendly: false,
    },
    "Tricep Pushdowns": {
        equipment: ["cable"],
        difficulty: "Beginner",
        movementPattern: "elbow extension",
        freeWeightAlternatives: ["Overhead Tricep Extension", "Close-Grip Bench Press", "Skullcrushers"],
        minimalEquipmentAlternatives: ["Overhead Tricep Extension", "Close-Grip Bench Press"],
        homeGymFriendly: false,
    },
    "Incline Barbell Press": {
        equipment: ["barbell", "bench"],
        difficulty: "Intermediate",
        movementPattern: "incline press",
        freeWeightAlternatives: ["Incline DB Press", "Dumbbell Bench Press", "Floor Press"],
        minimalEquipmentAlternatives: ["Floor Press", "Push-ups"],
        homeGymFriendly: true,
    },
    "Pec Deck": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "chest isolation",
        freeWeightAlternatives: ["Dumbbell Bench Press", "Push-ups", "Floor Press"],
        minimalEquipmentAlternatives: ["Push-ups", "Floor Press"],
        homeGymFriendly: false,
    },
    "Arnold Press": {
        equipment: ["dumbbell", "bench"],
        difficulty: "Intermediate",
        movementPattern: "vertical press",
        freeWeightAlternatives: ["Seated DB Press", "Barbell OHP", "Landmine Press"],
        minimalEquipmentAlternatives: ["Barbell OHP", "Landmine Press"],
        homeGymFriendly: true,
    },
    "Lateral Raises": {
        equipment: ["dumbbell"],
        difficulty: "Beginner",
        movementPattern: "shoulder abduction",
        freeWeightAlternatives: ["Cable Lateral Raises", "Bent-Over Rear Delt Flyes", "Arnold Press"],
        minimalEquipmentAlternatives: ["Lateral Raises", "Bent-Over Rear Delt Flyes"],
        homeGymFriendly: true,
    },
    "Skullcrushers": {
        equipment: ["barbell", "bench"],
        difficulty: "Intermediate",
        movementPattern: "elbow extension",
        freeWeightAlternatives: ["Overhead Tricep Extension", "Close-Grip Bench Press", "JM Press"],
        minimalEquipmentAlternatives: ["Overhead Tricep Extension", "Close-Grip Bench Press"],
        homeGymFriendly: true,
    },
    "Barbell Rows": {
        equipment: ["barbell"],
        difficulty: "Intermediate",
        movementPattern: "horizontal pull",
        freeWeightAlternatives: ["Chest-Supported Row", "Single-Arm Rows", "Inverted Rows"],
        minimalEquipmentAlternatives: ["Single-Arm Rows", "Inverted Rows"],
        homeGymFriendly: true,
    },
    "Pull-ups": {
        equipment: ["bodyweight", "pull-up-bar"],
        difficulty: "Intermediate",
        movementPattern: "vertical pull",
        freeWeightAlternatives: ["Inverted Rows", "Chest-Supported Row", "Single-Arm Rows"],
        minimalEquipmentAlternatives: ["Inverted Rows", "Single-Arm Rows"],
    },
    "Seated Cable Rows": {
        equipment: ["cable"],
        difficulty: "Beginner",
        movementPattern: "horizontal pull",
        freeWeightAlternatives: ["Chest-Supported Row", "Single-Arm Rows", "Barbell Rows"],
        minimalEquipmentAlternatives: ["Single-Arm Rows", "Inverted Rows"],
        homeGymFriendly: false,
    },
    "Face Pulls": {
        equipment: ["cable"],
        difficulty: "Beginner",
        movementPattern: "rear delt / scapular retraction",
        freeWeightAlternatives: ["Bent-Over Rear Delt Flyes", "Reverse Pec Deck", "Inverted Rows"],
        minimalEquipmentAlternatives: ["Bent-Over Rear Delt Flyes"],
        homeGymFriendly: false,
    },
    "EZ-Bar Curls": {
        equipment: ["barbell"],
        difficulty: "Beginner",
        movementPattern: "elbow flexion",
        freeWeightAlternatives: ["Dumbbell Curls", "Hammer Curls", "Preacher Curls"],
        minimalEquipmentAlternatives: ["Dumbbell Curls", "Hammer Curls"],
        homeGymFriendly: true,
    },
    "Hammer Curls": {
        equipment: ["dumbbell"],
        difficulty: "Beginner",
        movementPattern: "neutral-grip elbow flexion",
        freeWeightAlternatives: ["Dumbbell Curls", "EZ-Bar Curls", "Preacher Curls"],
        minimalEquipmentAlternatives: ["Dumbbell Curls", "Hammer Curls"],
        homeGymFriendly: true,
    },
    "Single-Arm Rows": {
        equipment: ["dumbbell", "bench"],
        difficulty: "Beginner",
        movementPattern: "unilateral horizontal pull",
        freeWeightAlternatives: ["Chest-Supported Row", "Barbell Rows", "Inverted Rows"],
        minimalEquipmentAlternatives: ["Single-Arm Rows", "Inverted Rows"],
        homeGymFriendly: true,
    },
    "Close-Grip Pulldowns": {
        equipment: ["cable"],
        difficulty: "Beginner",
        movementPattern: "vertical pull",
        freeWeightAlternatives: ["Pull-ups", "Inverted Rows", "Single-Arm Rows"],
        minimalEquipmentAlternatives: ["Inverted Rows", "Single-Arm Rows"],
        homeGymFriendly: false,
    },
    "Straight-Arm Pulldowns": {
        equipment: ["cable"],
        difficulty: "Beginner",
        movementPattern: "lat isolation",
        freeWeightAlternatives: ["Dumbbell Pullover", "Pull-ups", "Single-Arm Rows"],
        minimalEquipmentAlternatives: ["Dumbbell Pullover", "Inverted Rows"],
        homeGymFriendly: false,
    },
    "Reverse Pec Deck": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "rear delt / scapular control",
        freeWeightAlternatives: ["Bent-Over Rear Delt Flyes", "Face Pulls", "Inverted Rows"],
        minimalEquipmentAlternatives: ["Bent-Over Rear Delt Flyes"],
        homeGymFriendly: false,
    },
    "Preacher Curls": {
        equipment: ["dumbbell", "bench"],
        difficulty: "Beginner",
        movementPattern: "strict elbow flexion",
        freeWeightAlternatives: ["Dumbbell Curls", "EZ-Bar Curls", "Hammer Curls"],
        minimalEquipmentAlternatives: ["Dumbbell Curls", "Hammer Curls"],
        homeGymFriendly: true,
    },
    "Barbell Squats": {
        equipment: ["barbell"],
        difficulty: "Intermediate",
        movementPattern: "squat",
        freeWeightAlternatives: ["Front Squat", "Goblet Squat", "Bulgarian Split Squat"],
        minimalEquipmentAlternatives: ["Goblet Squat", "Bulgarian Split Squat"],
        homeGymFriendly: true,
    },
    "RDLs": {
        equipment: ["barbell"],
        difficulty: "Intermediate",
        movementPattern: "hip hinge",
        freeWeightAlternatives: ["Bulgarian Split Squat", "Goblet Squat", "Nordic Hamstring Curl"],
        minimalEquipmentAlternatives: ["Bulgarian Split Squat", "Nordic Hamstring Curl"],
        homeGymFriendly: true,
    },
    "Leg Press": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "machine squat",
        freeWeightAlternatives: ["Goblet Squat", "Front Squat", "Bulgarian Split Squat"],
        minimalEquipmentAlternatives: ["Goblet Squat", "Bulgarian Split Squat"],
        homeGymFriendly: false,
    },
    "Lying Leg Curls": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "knee flexion",
        freeWeightAlternatives: ["Nordic Hamstring Curl", "RDLs", "Bulgarian Split Squat"],
        minimalEquipmentAlternatives: ["Nordic Hamstring Curl", "Bulgarian Split Squat"],
        homeGymFriendly: false,
    },
    "Calf Raises": {
        equipment: ["bodyweight", "dumbbell"],
        difficulty: "Beginner",
        movementPattern: "plantar flexion",
        freeWeightAlternatives: ["Single-Leg Calf Raises", "Farmer Carry", "Walking Lunges"],
        minimalEquipmentAlternatives: ["Single-Leg Calf Raises", "Walking Lunges"],
        homeGymFriendly: true,
    },
    "Hack Squats": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "machine squat",
        freeWeightAlternatives: ["Front Squat", "Goblet Squat", "Bulgarian Split Squat"],
        minimalEquipmentAlternatives: ["Goblet Squat", "Bulgarian Split Squat"],
        homeGymFriendly: false,
    },
    "Leg Extensions": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "knee extension",
        freeWeightAlternatives: ["Goblet Squat", "Bulgarian Split Squat", "Walking Lunges"],
        minimalEquipmentAlternatives: ["Goblet Squat", "Bulgarian Split Squat"],
        homeGymFriendly: false,
    },
    "Seated Leg Curls": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "knee flexion",
        freeWeightAlternatives: ["Nordic Hamstring Curl", "RDLs", "Bulgarian Split Squat"],
        minimalEquipmentAlternatives: ["Nordic Hamstring Curl", "Bulgarian Split Squat"],
        homeGymFriendly: false,
    },
    "Walking Lunges": {
        equipment: ["dumbbell", "bodyweight"],
        difficulty: "Beginner",
        movementPattern: "split squat / locomotion",
        freeWeightAlternatives: ["Bulgarian Split Squat", "Goblet Squat", "Front Squat"],
        minimalEquipmentAlternatives: ["Bulgarian Split Squat", "Walking Lunges"],
        homeGymFriendly: true,
    },
    "Treadmill Incline Walk": {
        equipment: ["machine"],
        difficulty: "Beginner",
        movementPattern: "low-intensity conditioning",
        freeWeightAlternatives: ["Farmer Carry", "Walking Lunges", "Mobility Work"],
        minimalEquipmentAlternatives: ["Farmer Carry", "Mobility Work"],
        homeGymFriendly: false,
    },
    "Mobility Work": {
        equipment: ["bodyweight"],
        difficulty: "Beginner",
        movementPattern: "mobility flow",
        freeWeightAlternatives: ["Mobility Work", "Plank", "Farmer Carry"],
        minimalEquipmentAlternatives: ["Mobility Work", "Plank"],
        homeGymFriendly: true,
    },
};

export const ADDITIONAL_WIKI_DATA: ExerciseWiki[] = [
    {
        id: "e-push-ups",
        name: "Push-ups",
        category: "Push",
        muscles: {
            primary: ["Pectoralis Major", "Triceps Brachii"],
            secondary: ["Anterior Deltoids", "Serratus Anterior", "Core"],
        },
        biomechanics:
            "A closed-chain horizontal press where the hands stay fixed and the body moves. Push-ups teach full-body tension, scapular control, and pressing mechanics without needing a bench or rack, making them one of the most scalable access-friendly pressing movements.",
        cues: [
            "Screw your hands into the floor and keep shoulders slightly externally rotated.",
            "Brace glutes and abs before the first rep so the torso moves as one unit.",
            "Lower your chest between the hands, not your head toward the floor.",
            "Finish by reaching long through the upper back without shrugging.",
        ],
        commonMistakes: [
            "Letting hips sag and turning the rep into a spinal extension drill.",
            "Flaring elbows hard to the sides instead of finding a strong pressing groove.",
            "Cutting ROM short and never training the bottom position.",
        ],
        alternatives: ["Dumbbell Bench Press", "Floor Press", "Close-Grip Bench Press"],
        notes:
            "Push-ups are the ultimate fallback when equipment is limited. Elevate the hands to make them easier, load a backpack or use tempo pauses to make them harder, and keep them in rotation even when you have access to heavier pressing.",
        equipment: ["bodyweight"],
        difficulty: "Beginner",
        movementPattern: "horizontal press",
        bestFor: ["minimal-equipment training", "joint-friendly pressing volume", "travel workouts"],
        setupChecklist: [
            "Hands just outside shoulder width.",
            "Feet together or hip width depending on stability needs.",
            "Full-body plank before every rep.",
        ],
        freeWeightAlternatives: ["Dumbbell Bench Press", "Floor Press", "Close-Grip Bench Press"],
        minimalEquipmentAlternatives: ["Push-ups", "Floor Press"],
        homeGymFriendly: true,
    },
    {
        id: "e-dumbbell-bench-press",
        name: "Dumbbell Bench Press",
        category: "Push",
        muscles: {
            primary: ["Pectoralis Major"],
            secondary: ["Anterior Deltoids", "Triceps Brachii", "Serratus Anterior"],
        },
        biomechanics:
            "A free-weight horizontal press with independent loading per arm. Dumbbells allow a larger range of motion than a barbell and force each side to stabilize and produce force on its own, which is excellent when a rack or spotter is unavailable.",
        cues: [
            "Kick or clean the dumbbells into place before setting the shoulder blades.",
            "Lower until elbows are slightly below the bench line while staying in control.",
            "Press up and slightly in, but do not bang the dumbbells together.",
        ],
        commonMistakes: [
            "Dumping the dumbbells too deep and losing shoulder position.",
            "Letting wrists fold back under load.",
            "Rushing the setup and wasting energy before the first rep even starts.",
        ],
        alternatives: ["Bench Press", "Floor Press", "Push-ups"],
        notes:
            "If you train alone or lack a rack, dumbbell benching is often the smartest default pressing lift. It preserves chest overload while giving you a safer bailout path and more freedom to adjust shoulder comfort.",
        equipment: ["dumbbell", "bench"],
        difficulty: "Beginner",
        movementPattern: "horizontal press",
        bestFor: ["solo training", "reducing left-right imbalances", "home gym setups"],
        setupChecklist: [
            "Set dumbbells at the knees before the kick-up.",
            "Retract shoulder blades before the first descent.",
            "Keep forearms stacked under the bells at the bottom.",
        ],
        freeWeightAlternatives: ["Bench Press", "Floor Press", "Push-ups"],
        minimalEquipmentAlternatives: ["Floor Press", "Push-ups"],
        homeGymFriendly: true,
    },
    {
        id: "e-floor-press",
        name: "Floor Press",
        category: "Push",
        muscles: {
            primary: ["Pectoralis Major", "Triceps Brachii"],
            secondary: ["Anterior Deltoids"],
        },
        biomechanics:
            "A horizontal press performed from the floor with the elbows stopping against the ground. The shortened range makes it shoulder-friendly, reinforces upper-arm positioning, and gives you a safe heavy press when you do not have a bench.",
        cues: [
            "Set the upper back first and let the elbows lightly touch the floor each rep.",
            "Pause briefly on the floor to own the bottom position.",
            "Drive the weight up without bouncing the elbows off the ground.",
        ],
        commonMistakes: [
            "Rolling the shoulders forward when the elbows make contact.",
            "Using the floor as a trampoline instead of a control point.",
            "Starting too heavy and struggling to set up safely.",
        ],
        alternatives: ["Dumbbell Bench Press", "Push-ups", "Close-Grip Bench Press"],
        notes:
            "The floor press is one of the easiest swaps for machine or bench-based chest work when space is tight. It also pairs well with heavy pressing blocks because it limits shoulder stress in the bottom range.",
        equipment: ["barbell", "dumbbell"],
        difficulty: "Beginner",
        movementPattern: "horizontal press",
        bestFor: ["bench-free home gyms", "shoulder-friendly pressing", "lockout strength"],
        setupChecklist: [
            "Choose a load you can safely get into position.",
            "Keep wrists stacked and elbows at a strong pressing angle.",
            "Use a pause instead of bouncing.",
        ],
        freeWeightAlternatives: ["Dumbbell Bench Press", "Push-ups", "Close-Grip Bench Press"],
        minimalEquipmentAlternatives: ["Push-ups"],
        homeGymFriendly: true,
    },
    {
        id: "e-barbell-ohp",
        name: "Barbell OHP",
        category: "Push",
        muscles: {
            primary: ["Anterior Deltoids", "Triceps Brachii"],
            secondary: ["Upper Chest", "Upper Trapezius", "Core"],
        },
        biomechanics:
            "A standing vertical press that demands full-body bracing while the arms travel overhead. Because the torso must stay organized under load, the barbell overhead press doubles as both a shoulder builder and a total-body skill lift.",
        cues: [
            "Squeeze glutes and ribs down before the bar leaves the shoulders.",
            "Move your head back slightly to clear the bar path, then drive through at lockout.",
            "Finish with the bar stacked over mid-foot, not out in front of you.",
        ],
        commonMistakes: [
            "Turning every rep into an incline bench by leaning back excessively.",
            "Pressing around the face instead of moving the head around the bar.",
            "Losing wrist position and letting the bar sit too far in the fingers.",
        ],
        alternatives: ["Seated DB Press", "Landmine Press", "Arnold Press"],
        notes:
            "When cables and machines are unavailable, the overhead press becomes a cornerstone. It gives you heavy shoulder loading with almost no setup beyond a barbell and enough room to press overhead.",
        equipment: ["barbell"],
        difficulty: "Intermediate",
        movementPattern: "vertical press",
        bestFor: ["stronger shoulders", "home gym programming", "whole-body pressing tension"],
        setupChecklist: [
            "Rack height at upper chest.",
            "Hands just outside shoulders.",
            "Brace abs and glutes before every rep.",
        ],
        freeWeightAlternatives: ["Seated DB Press", "Landmine Press", "Arnold Press"],
        minimalEquipmentAlternatives: ["Landmine Press", "Push-ups"],
        homeGymFriendly: true,
    },
    {
        id: "e-landmine-press",
        name: "Landmine Press",
        category: "Push",
        muscles: {
            primary: ["Anterior Deltoids", "Upper Chest"],
            secondary: ["Serratus Anterior", "Triceps Brachii", "Core"],
        },
        biomechanics:
            "An angled press that sits between horizontal and vertical pressing. The arcing path is usually friendlier on irritated shoulders than strict overhead work, and a single barbell in a landmine setup gives you a versatile press without machines.",
        cues: [
            "Keep the working-side ribcage stacked over the pelvis.",
            "Press up and slightly forward along the arc of the bar.",
            "Reach at the top without shrugging aggressively.",
        ],
        commonMistakes: [
            "Over-rotating the torso and turning it into a twist instead of a press.",
            "Letting the elbow flare too far out from the bar path.",
            "Using too much load and losing the smooth arc.",
        ],
        alternatives: ["Barbell OHP", "Seated DB Press", "Arnold Press"],
        notes:
            "The landmine press is a great bridge movement when full overhead pressing is uncomfortable or when you want a strong free-weight alternative to shoulder machines.",
        equipment: ["landmine", "barbell"],
        difficulty: "Beginner",
        movementPattern: "angled press",
        bestFor: ["shoulder-friendly pressing", "limited equipment gyms", "single-arm stability work"],
        setupChecklist: [
            "Anchor the bar securely.",
            "Stand tall with a staggered or half-kneeling stance.",
            "Own the lockout instead of rushing the top.",
        ],
        freeWeightAlternatives: ["Barbell OHP", "Seated DB Press", "Arnold Press"],
        minimalEquipmentAlternatives: ["Push-ups"],
        homeGymFriendly: true,
    },
    {
        id: "e-overhead-tricep-extension",
        name: "Overhead Tricep Extension",
        category: "Push",
        muscles: {
            primary: ["Triceps Brachii (Long Head)"],
            secondary: ["Anconeus", "Core"],
        },
        biomechanics:
            "An elbow extension pattern with the shoulder in flexion, placing the long head of the triceps under stretch. This is one of the best ways to keep arm work productive when you do not have access to cable stacks.",
        cues: [
            "Keep upper arms mostly fixed and let the elbows bend deeply behind the head.",
            "Use a neutral grip if straight bars bother the wrists or elbows.",
            "Control the lowering phase so the stretch actually loads the triceps.",
        ],
        commonMistakes: [
            "Flaring elbows wide and losing the long-head stretch.",
            "Going too heavy and turning the movement into a weird press.",
            "Cutting the bottom short because the position feels unstable.",
        ],
        alternatives: ["Skullcrushers", "Close-Grip Bench Press", "Tricep Pushdowns"],
        notes:
            "If your routine currently depends on pushdowns, an overhead extension is one of the easiest free-weight substitutions to keep triceps training complete.",
        equipment: ["dumbbell", "barbell"],
        difficulty: "Beginner",
        movementPattern: "overhead elbow extension",
        bestFor: ["arm size", "long-head triceps work", "machine-free accessory training"],
        setupChecklist: [
            "Pick an implement you can stabilize overhead.",
            "Brace ribs down before starting the set.",
            "Use full ROM before chasing extra load.",
        ],
        freeWeightAlternatives: ["Skullcrushers", "Close-Grip Bench Press", "Tricep Pushdowns"],
        minimalEquipmentAlternatives: ["Push-ups"],
        homeGymFriendly: true,
    },
    {
        id: "e-close-grip-bench-press",
        name: "Close-Grip Bench Press",
        category: "Push",
        muscles: {
            primary: ["Triceps Brachii"],
            secondary: ["Pectoralis Major", "Anterior Deltoids"],
        },
        biomechanics:
            "A pressing variation with a narrower hand position that shifts emphasis toward elbow extension. It is a strong swap when cable tricep work is unavailable because it lets you load the triceps heavily with only a bench and bar.",
        cues: [
            "Bring the grip in but keep wrists stacked and forearms vertical at the bottom.",
            "Lower to the lower chest / upper sternum with elbows tracking close to the torso.",
            "Press smoothly without letting shoulders roll forward.",
        ],
        commonMistakes: [
            "Going so narrow that wrists and elbows get forced into ugly positions.",
            "Touching too high on the chest and turning it into a shoulder-dominant press.",
            "Forgetting to keep upper-back tension like a standard bench.",
        ],
        alternatives: ["Bench Press", "Overhead Tricep Extension", "Skullcrushers"],
        notes:
            "Close-grip pressing is one of the best machine-free ways to keep heavy tricep stimulus in a program while still carrying over to bigger compound lifts.",
        equipment: ["barbell", "bench"],
        difficulty: "Intermediate",
        movementPattern: "horizontal press",
        bestFor: ["machine-free tricep work", "bench lockout strength", "upper-body strength blocks"],
        setupChecklist: [
            "Hands just inside shoulder width.",
            "Keep shoulders pinned and elbows controlled.",
            "Own the pause on the chest if bar speed is inconsistent.",
        ],
        freeWeightAlternatives: ["Bench Press", "Overhead Tricep Extension", "Skullcrushers"],
        minimalEquipmentAlternatives: ["Push-ups", "Floor Press"],
        homeGymFriendly: true,
    },
    {
        id: "e-chest-supported-row",
        name: "Chest-Supported Row",
        category: "Pull",
        muscles: {
            primary: ["Rhomboids", "Middle Trapezius", "Latissimus Dorsi"],
            secondary: ["Posterior Deltoids", "Biceps Brachii"],
        },
        biomechanics:
            "A horizontal row performed with the torso supported on a bench. By removing the lower-back stability demand, it lets you hammer upper-back and lat work with dumbbells when cable or machine rows are unavailable.",
        cues: [
            "Set the bench angle so the chest stays glued to the pad throughout the set.",
            "Lead the rep with the elbows and pause near the torso.",
            "Let the shoulder blades move at the bottom to get a full stretch.",
        ],
        commonMistakes: [
            "Turning the row into a shrug by leading with the traps.",
            "Bouncing off the pad instead of controlling the negative.",
            "Using too much torso rotation to move the load.",
        ],
        alternatives: ["Barbell Rows", "Single-Arm Rows", "Inverted Rows"],
        notes:
            "Chest-supported rows are one of the best home-gym replacements for seated cable rows because they keep the back target high while reducing spinal fatigue.",
        equipment: ["dumbbell", "bench"],
        difficulty: "Beginner",
        movementPattern: "horizontal pull",
        bestFor: ["machine-free rowing", "upper-back hypertrophy", "lower-back fatigue management"],
        setupChecklist: [
            "Bench angle around 30-45 degrees.",
            "Chest stays heavy on the pad.",
            "Let the arms fully extend between reps.",
        ],
        freeWeightAlternatives: ["Barbell Rows", "Single-Arm Rows", "Inverted Rows"],
        minimalEquipmentAlternatives: ["Inverted Rows"],
        homeGymFriendly: true,
    },
    {
        id: "e-inverted-rows",
        name: "Inverted Rows",
        category: "Pull",
        muscles: {
            primary: ["Rhomboids", "Latissimus Dorsi"],
            secondary: ["Biceps Brachii", "Posterior Deltoids", "Core"],
        },
        biomechanics:
            "A bodyweight horizontal pull where the torso stays rigid while the chest travels to a bar, rings, or a sturdy setup. It is one of the best access-friendly options for lifters who do not have cables or row machines.",
        cues: [
            "Keep the body in a straight line from ankles to shoulders.",
            "Pull the chest toward the bar instead of craning the chin up.",
            "Use tempo pauses at the top before loading with added weight.",
        ],
        commonMistakes: [
            "Sagging the hips and losing the torso line.",
            "Half-repping because the bar is set too low or too high.",
            "Yanking with the arms before setting the shoulder blades.",
        ],
        alternatives: ["Pull-ups", "Chest-Supported Row", "Single-Arm Rows"],
        notes:
            "Inverted rows are a great bridge between machine pulls and full bodyweight pull-ups. They also make an excellent emergency swap when all you have is a bar and some floor space.",
        equipment: ["bodyweight", "pull-up-bar"],
        difficulty: "Beginner",
        movementPattern: "horizontal pull",
        bestFor: ["minimal-equipment pulling", "back volume without machines", "building toward pull-ups"],
        setupChecklist: [
            "Choose a stable bar height.",
            "Brace glutes and abs before the first rep.",
            "Adjust foot position to match your strength level.",
        ],
        freeWeightAlternatives: ["Chest-Supported Row", "Single-Arm Rows", "Pull-ups"],
        minimalEquipmentAlternatives: ["Inverted Rows"],
        homeGymFriendly: true,
    },
    {
        id: "e-dumbbell-curls",
        name: "Dumbbell Curls",
        category: "Pull",
        muscles: {
            primary: ["Biceps Brachii"],
            secondary: ["Brachialis", "Brachioradialis"],
        },
        biomechanics:
            "A classic supinated curl with each arm working independently. Dumbbells let you rotate naturally through the rep and make bicep work accessible in almost any training environment.",
        cues: [
            "Start from a full elbow extension without letting shoulders drift forward.",
            "Rotate into a strong supinated finish as you curl.",
            "Lower slower than you lift to keep tension on the biceps.",
        ],
        commonMistakes: [
            "Swinging the torso to pass the sticking point.",
            "Starting with the palms already fully supinated and losing range.",
            "Never training the long bottom range because the load is too heavy.",
        ],
        alternatives: ["EZ-Bar Curls", "Hammer Curls", "Preacher Curls"],
        notes:
            "If a machine arm station is not available, dumbbell curls cover the basics extremely well and make it easy to run unilateral or tempo-focused progressions.",
        equipment: ["dumbbell"],
        difficulty: "Beginner",
        movementPattern: "elbow flexion",
        bestFor: ["home gym arm work", "wrist-friendly curling", "unilateral arm balance"],
        setupChecklist: [
            "Stand tall with elbows slightly in front of the torso.",
            "Use a weight you can control on the lowering phase.",
            "Keep shoulders quiet during the curl.",
        ],
        freeWeightAlternatives: ["EZ-Bar Curls", "Hammer Curls", "Preacher Curls"],
        minimalEquipmentAlternatives: ["Dumbbell Curls", "Hammer Curls"],
        homeGymFriendly: true,
    },
    {
        id: "e-bent-over-rear-delt-flyes",
        name: "Bent-Over Rear Delt Flyes",
        category: "Pull",
        muscles: {
            primary: ["Posterior Deltoids"],
            secondary: ["Rhomboids", "Middle Trapezius", "External Rotators"],
        },
        biomechanics:
            "A free-weight horizontal abduction pattern for the rear delts and upper back. It is one of the cleanest substitutions for machine or cable rear-delt work when all you have is a pair of dumbbells.",
        cues: [
            "Hinge until the torso is close to parallel so the rear delts own the line of pull.",
            "Sweep the elbows out and slightly back rather than shrugging.",
            "Use small plates or dumbbells and keep the movement crisp.",
        ],
        commonMistakes: [
            "Going too heavy and turning the movement into a sloppy row.",
            "Standing too upright and losing rear-delt tension.",
            "Shrugging upward instead of opening the upper arm.",
        ],
        alternatives: ["Reverse Pec Deck", "Face Pulls", "Inverted Rows"],
        notes:
            "Rear-delt flyes are easy to overlook, but they are a strong no-machine answer when you need posture, shoulder balance, and upper-back volume.",
        equipment: ["dumbbell"],
        difficulty: "Beginner",
        movementPattern: "rear delt isolation",
        bestFor: ["machine-free rear delt work", "posture balance", "shoulder health"],
        setupChecklist: [
            "Use a stable hip hinge.",
            "Keep neck long and chest slightly open.",
            "Choose a load that lets the rear delts do the work.",
        ],
        freeWeightAlternatives: ["Face Pulls", "Reverse Pec Deck", "Inverted Rows"],
        minimalEquipmentAlternatives: ["Bent-Over Rear Delt Flyes"],
        homeGymFriendly: true,
    },
    {
        id: "e-dumbbell-pullover",
        name: "Dumbbell Pullover",
        category: "Pull",
        muscles: {
            primary: ["Latissimus Dorsi", "Serratus Anterior"],
            secondary: ["Pectoralis Major", "Long Head of Triceps"],
        },
        biomechanics:
            "A shoulder extension pattern performed from a bench or the floor. It bridges the gap between chest and lat work and gives you a free-weight option when you need a replacement for cable pullovers or straight-arm pulldowns.",
        cues: [
            "Keep a soft elbow bend and move from the shoulders, not the elbows.",
            "Lower only as far as you can maintain ribs-down control.",
            "Pull the weight back over the torso using lats and serratus, not low-back arching.",
        ],
        commonMistakes: [
            "Overextending the spine to fake more range of motion.",
            "Turning it into a tricep extension with too much elbow bend.",
            "Using a load that forces a short, stiff arc.",
        ],
        alternatives: ["Straight-Arm Pulldowns", "Pull-ups", "Single-Arm Rows"],
        notes:
            "A pullover is a smart free-weight bridge when you still want some lat isolation but do not have access to cable stations.",
        equipment: ["dumbbell", "bench"],
        difficulty: "Intermediate",
        movementPattern: "shoulder extension",
        bestFor: ["cable-free lat isolation", "upper-body accessory work", "serratus control"],
        setupChecklist: [
            "Use a bench or floor setup that keeps your torso stable.",
            "Lock in ribcage position before lowering the weight.",
            "Start lighter than you think.",
        ],
        freeWeightAlternatives: ["Straight-Arm Pulldowns", "Pull-ups", "Single-Arm Rows"],
        minimalEquipmentAlternatives: ["Inverted Rows"],
        homeGymFriendly: true,
    },
    {
        id: "e-goblet-squat",
        name: "Goblet Squat",
        category: "Legs",
        muscles: {
            primary: ["Quadriceps", "Gluteus Maximus"],
            secondary: ["Adductors", "Core", "Upper Back"],
        },
        biomechanics:
            "A front-loaded squat with a dumbbell or kettlebell held at chest height. The anterior load helps counterbalance the hips, making it one of the easiest access-friendly squat patterns for lifters without racks or machine legs work.",
        cues: [
            "Keep elbows tucked and the load tight to the torso.",
            "Sit between the heels instead of folding forward over the knees.",
            "Use the pause at the bottom to own depth and position.",
        ],
        commonMistakes: [
            "Holding the weight away from the chest and straining the arms.",
            "Turning the movement into a good morning because the load is too heavy.",
            "Rushing the descent and bouncing out of depth.",
        ],
        alternatives: ["Front Squat", "Bulgarian Split Squat", "Barbell Squats"],
        notes:
            "For many home gyms, goblet squats are the default quad-builder. They also make an excellent machine-free replacement when a program originally leaned on hack squats, leg presses, or leg extensions.",
        equipment: ["dumbbell", "kettlebell"],
        difficulty: "Beginner",
        movementPattern: "squat",
        bestFor: ["machine-free quad work", "learning squat mechanics", "travel or apartment gyms"],
        setupChecklist: [
            "Brace before sitting down into the rep.",
            "Keep the load high and tight.",
            "Stay patient in the bottom position.",
        ],
        freeWeightAlternatives: ["Front Squat", "Bulgarian Split Squat", "Barbell Squats"],
        minimalEquipmentAlternatives: ["Goblet Squat", "Bulgarian Split Squat"],
        homeGymFriendly: true,
    },
    {
        id: "e-front-squat",
        name: "Front Squat",
        category: "Legs",
        muscles: {
            primary: ["Quadriceps"],
            secondary: ["Gluteus Maximus", "Upper Back", "Core"],
        },
        biomechanics:
            "A front-loaded barbell squat that drives a more upright torso than back squats. It is a great free-weight substitute for quad-heavy machine work because it keeps knee demand high without needing a leg press or hack squat.",
        cues: [
            "Drive elbows high and keep the upper back proud.",
            "Brace hard before each descent so the bar stays stacked over the mid-foot.",
            "Push the floor away while keeping the chest tall.",
        ],
        commonMistakes: [
            "Letting elbows drop and turning the movement into a forward fold.",
            "Rushing the unrack and losing rack position before the set starts.",
            "Using depth that the torso cannot maintain under the current load.",
        ],
        alternatives: ["Barbell Squats", "Goblet Squat", "Bulgarian Split Squat"],
        notes:
            "If your gym setup has a barbell but no good leg machines, front squats are one of the cleanest ways to bias quads and trunk strength together.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "front-loaded squat",
        bestFor: ["quad emphasis", "machine-free leg blocks", "upright squat mechanics"],
        setupChecklist: [
            "Set a comfortable rack position before loading hard.",
            "Keep elbows high during the walkout.",
            "Choose a depth you can own without collapsing forward.",
        ],
        freeWeightAlternatives: ["Barbell Squats", "Goblet Squat", "Bulgarian Split Squat"],
        minimalEquipmentAlternatives: ["Goblet Squat"],
        homeGymFriendly: true,
    },
    {
        id: "e-bulgarian-split-squat",
        name: "Bulgarian Split Squat",
        category: "Legs",
        muscles: {
            primary: ["Quadriceps", "Gluteus Maximus"],
            secondary: ["Adductors", "Hamstrings", "Core"],
        },
        biomechanics:
            "A rear-foot-elevated split squat that loads one leg at a time through a deep range of motion. It is brutally effective for lower-body stimulus with minimal load and makes an outstanding fallback when machine leg stations are unavailable.",
        cues: [
            "Pick a stance that lets the front leg do the work instead of cramping the back hip.",
            "Descend straight down with a slight torso lean to keep tension on the front leg.",
            "Drive through the whole front foot and finish tall.",
        ],
        commonMistakes: [
            "Setting up too narrow and getting jammed into the back hip.",
            "Pushing mostly off the rear leg instead of the front leg.",
            "Rushing reps and turning balance into the limiting factor.",
        ],
        alternatives: ["Goblet Squat", "Walking Lunges", "Front Squat"],
        notes:
            "Split squats are one of the highest-return leg swaps available: huge stimulus, tiny equipment demand, and easy progressions through load, tempo, pauses, or added range.",
        equipment: ["dumbbell", "bench", "bodyweight"],
        difficulty: "Intermediate",
        movementPattern: "split squat",
        bestFor: ["home gym leg training", "single-leg strength", "machine-free quad and glute work"],
        setupChecklist: [
            "Bench height around knee level.",
            "Front foot far enough forward to hit depth cleanly.",
            "Start with bodyweight or light dumbbells first.",
        ],
        freeWeightAlternatives: ["Goblet Squat", "Walking Lunges", "Front Squat"],
        minimalEquipmentAlternatives: ["Bulgarian Split Squat"],
        homeGymFriendly: true,
    },
    {
        id: "e-nordic-hamstring-curl",
        name: "Nordic Hamstring Curl",
        category: "Legs",
        muscles: {
            primary: ["Hamstrings"],
            secondary: ["Gluteus Maximus", "Calves", "Core"],
        },
        biomechanics:
            "A bodyweight eccentric-heavy hamstring exercise where the knees act as the pivot and the hamstrings resist a forward fall. It is one of the strongest machine-free replacements for leg curls and a proven movement for building resilient hamstrings.",
        cues: [
            "Keep hips extended and torso straight as you lower.",
            "Fight the descent for as long as possible before using hands to catch.",
            "Use assistance bands or reduced range first if you are new to the movement.",
        ],
        commonMistakes: [
            "Breaking at the hips and losing the hamstring line of pull.",
            "Trying to force concentric reps before controlling the eccentric.",
            "Using a setup that is not secure enough for the feet.",
        ],
        alternatives: ["Lying Leg Curls", "Seated Leg Curls", "RDLs"],
        notes:
            "Nordics are a powerful answer when curl machines are unavailable. Even a few controlled eccentrics can keep posterior-chain training highly effective.",
        equipment: ["bodyweight", "band"],
        difficulty: "Advanced",
        movementPattern: "knee flexion",
        bestFor: ["machine-free hamstrings", "injury resilience", "strong eccentrics"],
        setupChecklist: [
            "Anchor the feet securely.",
            "Start with band assistance if needed.",
            "Keep hips open and do not hinge early.",
        ],
        freeWeightAlternatives: ["RDLs", "Bulgarian Split Squat", "Lying Leg Curls"],
        minimalEquipmentAlternatives: ["Nordic Hamstring Curl"],
        homeGymFriendly: true,
    },
    {
        id: "e-single-leg-calf-raises",
        name: "Single-Leg Calf Raises",
        category: "Legs",
        muscles: {
            primary: ["Gastrocnemius", "Soleus"],
            secondary: ["Tibialis Posterior", "Foot Intrinsics"],
        },
        biomechanics:
            "A unilateral plantarflexion pattern that increases effective load without needing a calf machine. Using one leg at a time makes it easy to create enough intensity with bodyweight, dumbbells, or a backpack.",
        cues: [
            "Use a step or plate so you can get a deep stretch at the bottom.",
            "Pause hard at the top instead of bouncing through the range.",
            "Train each side evenly even if one calf is clearly stronger.",
        ],
        commonMistakes: [
            "Rushing through tiny pulses with no meaningful range of motion.",
            "Letting the ankle roll out at the top.",
            "Failing to use any pause, stretch, or tempo to make bodyweight hard enough.",
        ],
        alternatives: ["Calf Raises", "Farmer Carry", "Walking Lunges"],
        notes:
            "Single-leg calf raises are the easiest way to keep lower-leg training alive without a dedicated machine. Elevation, pauses, and added load scale them surprisingly far.",
        equipment: ["bodyweight", "dumbbell"],
        difficulty: "Beginner",
        movementPattern: "plantar flexion",
        bestFor: ["home gym calves", "unilateral lower-leg balance", "minimal-equipment finisher work"],
        setupChecklist: [
            "Use a stable edge for full ROM.",
            "Track through the big toe and second toe.",
            "Pause in the stretched and contracted positions.",
        ],
        freeWeightAlternatives: ["Calf Raises", "Farmer Carry", "Walking Lunges"],
        minimalEquipmentAlternatives: ["Single-Leg Calf Raises"],
        homeGymFriendly: true,
    },
    {
        id: "e-power-clean",
        name: "Power Clean",
        category: "Pull",
        muscles: {
            primary: ["Gluteus Maximus", "Hamstrings", "Upper Trapezius"],
            secondary: ["Quadriceps", "Calves", "Core", "Forearms"],
        },
        biomechanics:
            "An Olympic-lift derivative that moves a barbell from the floor to the front rack without catching in a full squat. It trains explosive hip and knee extension, fast turnover, and full-body coordination while keeping the catch height accessible for strength programs.",
        cues: [
            "Push the floor away and keep the bar close through the first pull.",
            "Extend violently through the hips before pulling under the bar.",
            "Catch with elbows high, ribs down, and feet flat.",
        ],
        commonMistakes: [
            "Yanking with the arms before the legs finish driving.",
            "Letting the bar swing away from the body.",
            "Catching with low elbows and letting the bar crash into the wrists.",
        ],
        alternatives: ["Hang Power Clean", "Clean Pull", "High Pull"],
        notes:
            "Power cleans are best used for low-rep power work before the heavier strength sets. Keep the load crisp and stop sets when bar speed or catch quality drops.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "olympic clean",
        bestFor: ["power development", "athletic carryover", "barbell skill practice"],
        setupChecklist: [
            "Use a barbell setup that can be dropped or lowered safely.",
            "Start with the bar over mid-foot and shoulders slightly over the bar.",
            "Warm up the front rack before loading hard.",
        ],
        freeWeightAlternatives: ["Hang Power Clean", "Clean Pull", "High Pull"],
        minimalEquipmentAlternatives: ["Kettlebell Swings", "Jump Squats"],
        homeGymFriendly: false,
    },
    {
        id: "e-hang-power-clean",
        name: "Hang Power Clean",
        category: "Pull",
        muscles: {
            primary: ["Gluteus Maximus", "Hamstrings", "Upper Trapezius"],
            secondary: ["Quadriceps", "Core", "Forearms", "Rear Deltoids"],
        },
        biomechanics:
            "A power clean variation that starts from the hang instead of the floor. Removing the first pull lets the lifter focus on the explosive extension, bar path, and turnover that make Olympic movements useful for power training.",
        cues: [
            "Hinge to the hang with lats tight and the bar against the thighs.",
            "Jump tall before pulling under.",
            "Meet the bar in the front rack instead of letting it crash.",
        ],
        commonMistakes: [
            "Squatting the bar down instead of hinging to the hang.",
            "Bumping the bar forward with the hips.",
            "Catching narrow and unstable.",
        ],
        alternatives: ["Power Clean", "Clean Pull", "High Pull"],
        notes:
            "The hang power clean is often the cleanest entry point for Olympic-style work because it reduces setup complexity while still training speed and timing.",
        equipment: ["barbell"],
        difficulty: "Intermediate",
        movementPattern: "olympic clean",
        bestFor: ["learning clean timing", "explosive pulls", "low-rep power blocks"],
        setupChecklist: [
            "Stand tall before setting the hang position.",
            "Keep knuckles down and lats engaged.",
            "Use triples or doubles while technique is fresh.",
        ],
        freeWeightAlternatives: ["Power Clean", "Clean Pull", "High Pull"],
        minimalEquipmentAlternatives: ["Kettlebell Swings", "Jump Squats"],
        homeGymFriendly: false,
    },
    {
        id: "e-clean-pull",
        name: "Clean Pull",
        category: "Pull",
        muscles: {
            primary: ["Gluteus Maximus", "Hamstrings", "Upper Trapezius"],
            secondary: ["Quadriceps", "Calves", "Erector Spinae", "Forearms"],
        },
        biomechanics:
            "An Olympic pulling accessory that uses the clean setup and extension pattern without the turnover or catch. It overloads the pull, reinforces bar proximity, and builds the violent finish needed for cleans.",
        cues: [
            "Set up like a clean with the bar over mid-foot.",
            "Stay patient off the floor and accelerate past the knees.",
            "Finish tall with shoulders rising after the hips extend.",
        ],
        commonMistakes: [
            "Turning the pull into a deadlift followed by a shrug.",
            "Bending the arms early.",
            "Overextending backward instead of finishing vertically.",
        ],
        alternatives: ["Power Clean", "Hang Power Clean", "Snatch Pull"],
        notes:
            "Clean pulls are useful when you want Olympic-lift power without the technical demand of receiving the bar. They can be loaded heavier than cleans while keeping reps low and fast.",
        equipment: ["barbell"],
        difficulty: "Intermediate",
        movementPattern: "olympic clean pull",
        bestFor: ["clean strength", "explosive hip extension", "technical pull practice"],
        setupChecklist: [
            "Match your clean start position.",
            "Keep the bar brushing close to the legs.",
            "Reset each rep instead of bouncing from the floor.",
        ],
        freeWeightAlternatives: ["Power Clean", "Hang Power Clean", "Snatch Pull"],
        minimalEquipmentAlternatives: ["RDLs", "Kettlebell Swings"],
        homeGymFriendly: false,
    },
    {
        id: "e-power-snatch",
        name: "Power Snatch",
        category: "Pull",
        muscles: {
            primary: ["Gluteus Maximus", "Hamstrings", "Upper Trapezius"],
            secondary: ["Quadriceps", "Shoulders", "Core", "Forearms"],
        },
        biomechanics:
            "An Olympic-lift derivative that moves the bar from the floor to overhead in one explosive motion without receiving in a full squat. The wider grip and overhead catch demand speed, mobility, and precise bar path.",
        cues: [
            "Use a wide grip and keep the chest over the bar longer than you think.",
            "Drive vertically, then pull under fast.",
            "Catch with locked elbows and the bar stacked over mid-foot.",
        ],
        commonMistakes: [
            "Swinging the bar away and chasing it forward.",
            "Pressing out the catch instead of receiving with locked arms.",
            "Loading the lift before overhead mobility is ready.",
        ],
        alternatives: ["Hang Power Snatch", "Snatch Pull", "High Pull"],
        notes:
            "Power snatches belong early in the workout as crisp singles, doubles, or triples. Treat them as skill-power work, not conditioning fatigue.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "olympic snatch",
        bestFor: ["power development", "overhead athleticism", "bar speed"],
        setupChecklist: [
            "Confirm overhead lockout and shoulder comfort first.",
            "Set a wide grip that places the bar in the hip crease.",
            "Use light technique sets before adding load.",
        ],
        freeWeightAlternatives: ["Hang Power Snatch", "Snatch Pull", "High Pull"],
        minimalEquipmentAlternatives: ["Kettlebell Swings", "Jump Squats"],
        homeGymFriendly: false,
    },
    {
        id: "e-hang-power-snatch",
        name: "Hang Power Snatch",
        category: "Pull",
        muscles: {
            primary: ["Gluteus Maximus", "Hamstrings", "Upper Trapezius"],
            secondary: ["Shoulders", "Quadriceps", "Core", "Forearms"],
        },
        biomechanics:
            "A snatch variation that starts from the hang and catches overhead above a full squat. It narrows the focus to the explosive hip extension, close bar path, and fast punch under the bar.",
        cues: [
            "Hinge to the hang while keeping the bar close.",
            "Finish the jump before pulling under.",
            "Punch the bar overhead and receive with active shoulders.",
        ],
        commonMistakes: [
            "Letting the bar drift forward during the hinge.",
            "Catching soft through the elbows.",
            "Going too heavy and turning it into an awkward muscle snatch.",
        ],
        alternatives: ["Power Snatch", "Snatch Pull", "High Pull"],
        notes:
            "The hang power snatch is a strong choice when you want Olympic-style speed without the complexity of pulling from the floor.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "olympic snatch",
        bestFor: ["snatch timing", "overhead power", "technical warm-up blocks"],
        setupChecklist: [
            "Warm up shoulders and thoracic extension.",
            "Find a hang position that keeps the bar connected to the legs.",
            "Keep reps low enough that catches stay sharp.",
        ],
        freeWeightAlternatives: ["Power Snatch", "Snatch Pull", "High Pull"],
        minimalEquipmentAlternatives: ["Kettlebell Swings", "Jump Squats"],
        homeGymFriendly: false,
    },
    {
        id: "e-snatch",
        name: "Snatch",
        category: "Pull",
        muscles: {
            primary: ["Gluteus Maximus", "Hamstrings", "Upper Trapezius"],
            secondary: ["Quadriceps", "Shoulders", "Core", "Forearms"],
        },
        biomechanics:
            "A competition Olympic lift that takes the bar from the floor to overhead in one continuous motion and receives it in an overhead squat. It combines maximal speed, mobility, coordination, and overhead stability.",
        cues: [
            "Stay connected to the floor and keep the bar close through the pull.",
            "Finish tall, then pull under instead of pulling the bar up with the arms.",
            "Receive in a strong overhead squat with active shoulders.",
        ],
        commonMistakes: [
            "Rushing off the floor and losing position before the bar reaches the knees.",
            "Looping the bar forward instead of keeping it close.",
            "Trying to save missed catches with unstable shoulders.",
        ],
        alternatives: ["Power Snatch", "Hang Power Snatch", "Snatch Pull"],
        notes:
            "The snatch is highly technical and belongs in the program only when mobility, coaching, and safe equipment are available. Use light singles or doubles while learning.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "olympic snatch",
        bestFor: ["weightlifting skill", "speed-strength", "overhead mobility"],
        setupChecklist: [
            "Confirm overhead squat mobility before loading.",
            "Use a wide grip that keeps the bar close to the body.",
            "Practice with an empty bar until the catch is consistent.",
        ],
        freeWeightAlternatives: ["Power Snatch", "Hang Power Snatch", "Snatch Pull"],
        minimalEquipmentAlternatives: ["Kettlebell Swings", "Jump Squats"],
        homeGymFriendly: false,
    },
    {
        id: "e-clean-and-jerk",
        name: "Clean and Jerk",
        category: "Push",
        muscles: {
            primary: ["Quadriceps", "Gluteus Maximus", "Shoulders", "Triceps Brachii"],
            secondary: ["Hamstrings", "Upper Trapezius", "Core", "Forearms"],
        },
        biomechanics:
            "A competition Olympic lift that combines a clean from the floor to the shoulders with a jerk from the front rack to overhead. It trains explosive leg drive, receiving strength, and overhead power in one technical sequence.",
        cues: [
            "Make the clean first: close pull, fast turnover, high elbows.",
            "Reset the breath and feet before dipping for the jerk.",
            "Drive vertically and punch under to a locked-out overhead catch.",
        ],
        commonMistakes: [
            "Rushing the jerk before the front rack is stable.",
            "Letting the dip drift forward and pushing the bar out front.",
            "Treating the lift as a conditioning rep instead of a technical power movement.",
        ],
        alternatives: ["Power Clean", "Push Jerk", "Clean Pull"],
        notes:
            "Clean and jerks should be programmed as low-rep skill-power work. They are demanding, so place them early in the session and keep reps crisp.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "olympic clean and jerk",
        bestFor: ["weightlifting skill", "full-body power", "front-rack and overhead practice"],
        setupChecklist: [
            "Use a safe lifting area with room to miss or lower the bar.",
            "Warm up front rack, overhead lockout, and split or power jerk footwork.",
            "Keep loads light until both phases are reliable.",
        ],
        freeWeightAlternatives: ["Power Clean", "Push Jerk", "Clean Pull"],
        minimalEquipmentAlternatives: ["Barbell OHP", "Kettlebell Swings"],
        homeGymFriendly: false,
    },
    {
        id: "e-push-jerk",
        name: "Push Jerk",
        category: "Push",
        muscles: {
            primary: ["Anterior Deltoids", "Triceps Brachii", "Quadriceps"],
            secondary: ["Gluteus Maximus", "Upper Trapezius", "Core"],
        },
        biomechanics:
            "An Olympic overhead lift where the legs drive the bar upward and the lifter re-bends to receive it with locked arms. It allows heavier overhead loading than a strict press while training timing, aggression, and stable overhead positions.",
        cues: [
            "Dip straight down with the torso vertical.",
            "Drive hard through the legs before punching under.",
            "Catch with knees bent, elbows locked, and the bar stacked overhead.",
        ],
        commonMistakes: [
            "Dipping forward and pushing the bar out front.",
            "Pressing after the drive instead of dropping under.",
            "Receiving with soft elbows or loose ribs.",
        ],
        alternatives: ["Push Press", "Barbell OHP", "Power Clean"],
        notes:
            "Push jerks fit well as low-rep overhead power work. Keep them technical and use strict or push presses when the goal is pure shoulder hypertrophy.",
        equipment: ["barbell"],
        difficulty: "Advanced",
        movementPattern: "olympic jerk",
        bestFor: ["overhead power", "jerk practice", "athletic pressing"],
        setupChecklist: [
            "Start from a secure front rack.",
            "Practice dip-and-drive timing before heavy sets.",
            "Make sure the overhead catch is stable before adding load.",
        ],
        freeWeightAlternatives: ["Push Press", "Barbell OHP", "Power Clean"],
        minimalEquipmentAlternatives: ["Barbell OHP", "Landmine Press"],
        homeGymFriendly: false,
    },
    {
        id: "e-farmer-carry",
        name: "Farmer Carry",
        category: "Cardio/Mobility",
        muscles: {
            primary: ["Forearms", "Upper Trapezius", "Core"],
            secondary: ["Gluteus Medius", "Calves", "Lats"],
        },
        biomechanics:
            "A loaded carry where the challenge comes from walking tall under weight while resisting sway. It blends conditioning, grip, trunk stability, and posture work, making it a useful machine-free replacement for some cardio or loaded finisher slots.",
        cues: [
            "Stand tall and let the weights hang, not drift forward.",
            "Take short, controlled steps and breathe behind a braced trunk.",
            "Keep shoulders packed but not shrugged to the ears.",
        ],
        commonMistakes: [
            "Walking sloppy and fast instead of staying stacked under the load.",
            "Allowing one side to dip or twist excessively.",
            "Choosing weights so heavy that posture falls apart immediately.",
        ],
        alternatives: ["Treadmill Incline Walk", "Walking Lunges", "Plank"],
        notes:
            "Carries are one of the best 'I do not have the machine for this' answers in the whole app. They build work capacity while training grip, posture, and trunk stiffness with only dumbbells or kettlebells.",
        equipment: ["dumbbell", "kettlebell"],
        difficulty: "Beginner",
        movementPattern: "loaded carry",
        bestFor: ["conditioning without machines", "grip and trunk endurance", "finisher work"],
        setupChecklist: [
            "Pick a load you can move with clean posture.",
            "Walk tall and smooth.",
            "Use distance or time as the progression target.",
        ],
        freeWeightAlternatives: ["Walking Lunges", "Single-Leg Calf Raises", "Mobility Work"],
        minimalEquipmentAlternatives: ["Walking Lunges", "Plank"],
        homeGymFriendly: true,
    },
    {
        id: "e-plank",
        name: "Plank",
        category: "Core",
        muscles: {
            primary: ["Rectus Abdominis", "Transverse Abdominis"],
            secondary: ["Obliques", "Serratus Anterior", "Glutes"],
        },
        biomechanics:
            "An anti-extension core hold that teaches the trunk to stay stacked under tension. It is a low-equipment way to improve ribcage-pelvis control, which helps almost every compound lift in the program.",
        cues: [
            "Pull elbows toward toes without actually moving them.",
            "Squeeze glutes and keep ribs down.",
            "Breathe quietly behind the brace instead of holding your breath forever.",
        ],
        commonMistakes: [
            "Letting the low back sag while pretending the hold is still productive.",
            "Holding too long with poor position instead of shortening the set and improving tension.",
            "Looking too far forward and cranking the neck.",
        ],
        alternatives: ["Ab Wheel Rollout", "Hanging Leg Raises", "Farmer Carry"],
        notes:
            "A good plank is not filler. It is an excellent access-friendly way to build the trunk stiffness needed for better squats, presses, carries, and hinge work.",
        equipment: ["bodyweight"],
        difficulty: "Beginner",
        movementPattern: "anti-extension core",
        bestFor: ["minimal-equipment trunk work", "bracing practice", "daily consistency"],
        setupChecklist: [
            "Hands or elbows directly under shoulders.",
            "Glutes and abs squeezed before the timer starts.",
            "Stop when position fades, not when the timer becomes impressive.",
        ],
        freeWeightAlternatives: ["Farmer Carry", "Ab Wheel Rollout", "Hanging Leg Raises"],
        minimalEquipmentAlternatives: ["Plank"],
        homeGymFriendly: true,
    },
    {
        id: "e-hanging-leg-raises",
        name: "Hanging Leg Raises",
        category: "Core",
        muscles: {
            primary: ["Lower Rectus Abdominis", "Hip Flexors"],
            secondary: ["Obliques", "Lats", "Grip"],
        },
        biomechanics:
            "A hanging trunk-flexion pattern that also challenges shoulder and grip endurance. When controlled rather than swung, it is a high-value bodyweight core movement that fits well in equipment-limited setups with a pull-up bar.",
        cues: [
            "Set the ribcage and pelvis first before lifting the legs.",
            "Raise with control and avoid turning the set into a kip.",
            "Start with knees bent if straight-leg reps are not clean yet.",
        ],
        commonMistakes: [
            "Swinging to manufacture momentum.",
            "Arching hard at the bottom and losing trunk position.",
            "Chasing straight-leg reps before owning bent-knee control.",
        ],
        alternatives: ["Plank", "Ab Wheel Rollout", "Farmer Carry"],
        notes:
            "If you have a pull-up bar, hanging leg raises are one of the best bodyweight core add-ons you can make to a home or garage gym program.",
        equipment: ["bodyweight", "pull-up-bar"],
        difficulty: "Intermediate",
        movementPattern: "trunk flexion",
        bestFor: ["bodyweight core progression", "grip plus abs", "minimal equipment training"],
        setupChecklist: [
            "Start from a dead hang you can control.",
            "Posteriorly tilt the pelvis before lifting.",
            "Use bent knees before straight legs if needed.",
        ],
        freeWeightAlternatives: ["Ab Wheel Rollout", "Plank", "Farmer Carry"],
        minimalEquipmentAlternatives: ["Plank"],
        homeGymFriendly: true,
    },
    {
        id: "e-ab-wheel-rollout",
        name: "Ab Wheel Rollout",
        category: "Core",
        muscles: {
            primary: ["Rectus Abdominis", "Transverse Abdominis"],
            secondary: ["Lats", "Serratus Anterior", "Hip Flexors"],
        },
        biomechanics:
            "A dynamic anti-extension drill where the arms travel overhead while the torso resists spinal extension. It is one of the highest-return minimal-equipment core exercises if you can keep position under the moving lever.",
        cues: [
            "Keep ribs down and glutes lightly on as you roll forward.",
            "Only go as far as you can maintain a neutral trunk.",
            "Pull back with the abs and lats instead of hinging up with the hips.",
        ],
        commonMistakes: [
            "Rolling too far and dumping into lumbar extension.",
            "Using the hips to yank back instead of the trunk.",
            "Starting from standing before kneeling reps are crisp.",
        ],
        alternatives: ["Plank", "Hanging Leg Raises", "Farmer Carry"],
        notes:
            "An ab wheel or even a loaded barbell rollout gives you serious trunk training without a cable stack or machine station. Keep quality high and volume moderate.",
        equipment: ["barbell", "bodyweight"],
        difficulty: "Advanced",
        movementPattern: "anti-extension core",
        bestFor: ["high-tension core work", "minimal equipment progression", "bracing strength"],
        setupChecklist: [
            "Begin from the knees.",
            "Brace before moving the wheel.",
            "Cut range before form breaks.",
        ],
        freeWeightAlternatives: ["Plank", "Hanging Leg Raises", "Farmer Carry"],
        minimalEquipmentAlternatives: ["Plank"],
        homeGymFriendly: true,
    },
];
